### ISSUE TITLE
Broken link to Speed Crit

### ISSUE THREAD

**Issue by thb** [thoughtbot/design-sprint-guide#111]
on page https://design.thoughtbot.com/sprint-guide/exercises/group-critique/

=> [Speed Crit](https://design.thoughtbot.com/exercises/speed-crit.md)

**Comment by LkeMitchll** [comment]
@thb Thank-you for raising this issue. It should now be fixed.

**Comment by thb** [comment]
@LkeMitchll sure, thank you for this useful material
