### ISSUE TITLE
The visual appearance of internal content pages could be better

### ISSUE THREAD

**Issue by LkeMitchll** [thoughtbot/design-sprint-guide#24]
The current styling of internal pages is very basic, and is pretty much the inherited defaults, with a very simple wrapper around them.

There are few ways that we could improve the appearance of these pages:

- The line-length of content.
- The alignment of the content.
- Almost everything is in a long single column.
- The headings are large and very bold in comparison to the rest of the content.

In comparison the thoughtbot blog does a better job of all of these things within the same branding constraints.

**Comment by mijimenez** [comment]
Happy to help here as well.
