### ISSUE TITLE
The visual appearance and structure of the homepage could be better

### ISSUE THREAD

**Issue by LkeMitchll** [thoughtbot/design-sprint-guide#33]
The visual appearance and structure of the homepage is pretty basic at the moment and could be improved quite a bit, issues include:

- There are no images to make the content feel richer and more inviting.
- We are not taking advantage of the thoughtbot system of illustrations.
- The hierarchy is quite basic, single column, mostly, meaning the page is quite long.
- There is not enough visual variation to discern the difference between a list of exercises from a list of schedules.

**Comment by caro-sotillo** [comment]
Design: [https://www.figma.com/file/VcLx6U0cNVQmeFrrfA6LPc/Design-Sprint-Guide?node-id=1157%3A201&t=Hnl6iOwWN1h6C3c6-1](https://www.figma.com/file/VcLx6U0cNVQmeFrrfA6LPc/Design-Sprint-Guide?node-id=1157%3A201&t=Hnl6iOwWN1h6C3c6-1)



![Image](https://user-images.githubusercontent.com/107173882/207615061-6719ada7-68b6-425e-8557-c041a9cda1ba.png)

**Comment by LkeMitchll** [comment]
@fatimaburke Is there any more work to be done on this issue?

**Comment by fatimaburke** [comment]
@davidrnovak has done the latest work on this along with some structural refactors from @mijimenez but I'm not sure what's left.

**Comment by davidrnovak** [comment]
@LkeMitchll I'm going to tackle the Resource & Glossary and CTA sections today. I'll update the issue when I'm done with those sections.

**Comment by cpytel** [comment]
We're moving this to done. Anything that could be improved should have new, individual issues created for them. Thanks, all!
