### ISSUE TITLE
Netlify production setup

### ISSUE THREAD

**Issue by cpytel** [thoughtbot/design-sprint-guide#35]
Part of #18, this task is to track the work of getting Netlify ready for production.

- [x] Setup design.thoughtbot.com domain name
- [x] Enable https
- [x] Get the sprint to live at its `/sprint-guide` url
- [x] Redirect `/` to `/sprint-guide`

**Comment by cpytel** [comment]
@LkeMitchll Is this currently on the thoughtbot Netlify account? I don't see it. If not, can you transfer it in?

**Comment by LkeMitchll** [comment]
@cpytel No, I'll work on transferring.

**Comment by cpytel** [comment]
Ok, I've added you as a member of the team. Once you do that, you should be able to go to the settings on the site and the transfer button will allow you to transfer it to the thoughtbot team.

**Comment by cpytel** [comment]
@LkeMitchll @rtaibah - moving this discussion here. If we _don't_ want to keep the design sprint guide in its own repo, we can set it up so that design.thoughtbot.com/sprint-guide is a proxy to its own thing and design.thoughtbot.com is its own repo and netlify site.

My concern about that is that they then need to be completely separate and they can't share anything in terms of data, styles, etc.

So for that reason I'd lean towards having everything in one repository, but I wanted to make sure you know that its an option to have them be separate and all on the same domain.

What do you think?

**Comment by cpytel** [comment]
From @rtaibah commenting on the blog post:

> We started using a similar stack to the one you are using here for [DesignDot](https://github.com/thoughtbot/design-dot). Was hoping we can merge when we feel the level of maturity is right.

Ok, thanks. I can make that work.

> I am fine with doing this in the open. But I can't help but notice that our website and blog are private, is there a reason for that? And would these reasons extend to what we are doing here?

The reason why we opt opted for those to be private in the past is that folks have wanted to be able to have discussions about what we should or shouldn't do, or make blog posts that then get heavily discussed, edited, or even scrapped without having it all be public.

**Comment by cpytel** [comment]
This is all now live at https://design.thoughtbot.com/sprint-guide/

sshhh, don't tell anyone while we finish it up 😄
