### ISSUE TITLE
Migrate playbook/validation/product-design-sprint/converge

### ISSUE THREAD

**Issue by cpytel** [thoughtbot/design-sprint-guide#42]
https://thoughtbot.com/playbook/validation/product-design-sprint/converge

- [x] Move content we want to preserve into new guide
- [x] Add redirect to thoughtbot.com

**Comment by cpytel** [comment]
There was no content from the Playbook that was worth preserving that wasn't already moved over.

**Comment by cpytel** [comment]
Redirect is in https://github.com/thoughtbot/thoughtbot.com/pull/2674

**Comment by aspencer116** [comment]
Oh, I think we both picked this up at the same time! The only thing I noticed was the "identify conflicts" section which was under activities but didn't have its own page. I was going to add it as an activity to the new site.

**Comment by cpytel** [comment]
oh, I'm not looking at exercises as part of this these phase tickets, I'm literally only looking at the other copy in the phases. Feel free to handle the identify conflicts exercise. I had created another issue to confirm the individual exercises are migrated and redirected: https://github.com/thoughtbot/design-sprint-guide/issues/46

**Comment by cpytel** [comment]
oh, I see what you're saying, its not even on the list of exercises because it didn't have its own page.

**Comment by cpytel** [comment]
That'd be great for you to pick up!
