### ISSUE TITLE
Migrate Playbook exercises

### ISSUE THREAD

**Issue by cpytel** [thoughtbot/design-sprint-guide#46]
All of the Playbook exercises have been migrated into the new guide, but we need to remove them from the Playbook and put redirects in place.

- [x] 3-12-3
- [x] assumptions
- [x] back-burner
- [x] card-sorting
- [x] critical-path
- [x] five-whys
- [x] group-critique
- [x] mind-mapping
- [x] needs-wants-desires
- [x] pitch-practice
- [x] problem-statement
- [x] silent-critique
- [x] speedy-eights
- [x] storyboards
- [x] who-what-when-where

**Comment by cpytel** [comment]
@aspencer116 Do you want to take this whole issue since its sort of related ot the identify conflicts thing? Redirects can be added here: https://github.com/thoughtbot/thoughtbot.com/pull/2674

**Comment by aspencer116** [comment]
Yep, that makes sense!

**Comment by aspencer116** [comment]
Added two missing exercises https://github.com/thoughtbot/design-sprint-guide/pull/74

**Comment by aspencer116** [comment]
@cpytel I added redirects to your draft PR https://github.com/thoughtbot/thoughtbot.com/pull/2674/commits/6c6a271b6f1837dc8c1e2e7eb95b856bd4f87e52

**Comment by aspencer116** [comment]
Hope that was ok!
