### ISSUE TITLE
Redirect old guide exercises

### ISSUE THREAD

**Issue by cpytel** [thoughtbot/design-sprint-guide#55]
We need to be sure to add redirects for each of these exercises

- [x] understand/assumptions-board
- [x] understand/back-burner-board
- [x] understand/card-sorting
- [x] understand/critical-path
- [x] understand/five-whys
- [x] understand/needs-wants-desires
- [x] understand/pitch-practice
- [x] understand/problem-statement
- [x] understand/review-research
- [x] understand/who-what-where
- [x] converge/3-12-3
- [x] converge/final-storyboard
- [x] converge/identify-conflicts
- [x] converge/pitch-practice
- [x] diverge/group-critique
- [x] diverge/mind-mapping
- [x] diverge/pitch-practice
- [x] diverge/silent-critique
- [x] diverge/speedy-eights
- [x] diverge/story-boarding

**Comment by cpytel** [comment]
I've got this in progress, but I have to leave for the day.

**Comment by cpytel** [comment]
@aspencer116 I also came across the missing identify-conflicts. It appears in our guide as well. I'll let you bring in the Playbook version like we discussed as part of #46. I'll assume the slug is going to stay `identify-conflicts`, let me know if thats not the case.

**Comment by cpytel** [comment]
I've opened a PR for #65 and #66 for review and discussion.

**Comment by aspencer116** [comment]
Yes, that sounds good. I'll make sure the slug stays the same. Hoping to work on it this afternoon.

**Comment by cpytel** [comment]
Done in https://github.com/thoughtbot/thoughtbot.com/pull/2674
